name: "Test Variables"

on:
  workflow_dispatch:

jobs:
  test-github-env-context:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "var1=yellow" >> "$GITHUB_ENV"
    - name: step2
      run: |
        printf '%s\n' "$var1"
        printf '%s\n' "${{ env.var1 }}"
