name: "Test Variables"

on:
  workflow_dispatch:

jobs:
  test-github-env-context:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      id: step1
      run: |
        echo "var1=yellow" >> "$GITHUB_ENV"
        echo "var2=green" >> "$GITHUB_OUTPUT"
    - name: step2      
      run: |
        printf '%s\n' "$var1"
        printf '%s\n' "${{ env.var1 }}"
        printf '%s\n' "${{ steps.step1.outputs.var2 }}"
